# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmessage.proto\"H\n\x0f\x43omputationData\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x14\n\x0cpython_bytes\x18\x03 \x01(\x0c\x32H\n\nMPCService\x12:\n\x12GetComputationData\x12\x10.ComputationData\x1a\x10.ComputationData\"\x00\x62\x06proto3'
)




_COMPUTATIONDATA = _descriptor.Descriptor(
  name='ComputationData',
  full_name='ComputationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='ComputationData.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ComputationData.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='python_bytes', full_name='ComputationData.python_bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['ComputationData'] = _COMPUTATIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputationData = _reflection.GeneratedProtocolMessageType('ComputationData', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ComputationData)
  })
_sym_db.RegisterMessage(ComputationData)



_MPCSERVICE = _descriptor.ServiceDescriptor(
  name='MPCService',
  full_name='MPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=91,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetComputationData',
    full_name='MPCService.GetComputationData',
    index=0,
    containing_service=None,
    input_type=_COMPUTATIONDATA,
    output_type=_COMPUTATIONDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MPCSERVICE)

DESCRIPTOR.services_by_name['MPCService'] = _MPCSERVICE

# @@protoc_insertion_point(module_scope)
