# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmessage.proto\"\xe3\x01\n\x0f\x43omputationData\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.ComputationData.Type\x12\x14\n\x0cpython_bytes\x18\x02 \x01(\x0c\"\x94\x01\n\x04Type\x12\x08\n\x04NULL\x10\x00\x12\x0c\n\x08\x44\x41TA_DIM\x10\x01\x12\x0f\n\x0bSET_TRIPLET\x10\x0b\x12\x10\n\x0cTRIPLE_ARRAY\x10\x0c\x12\x12\n\x0eMUL_DATA_SHARE\x10\x14\x12\x14\n\x10MUL_OwnVal_SHARE\x10\x15\x12\x16\n\x12MUL_OtherVal_SHARE\x10\x16\x12\x0f\n\x0bRECEIVED_OK\x10\x63\x32H\n\nMPCService\x12:\n\x12GetComputationData\x12\x10.ComputationData\x1a\x10.ComputationData\"\x00\x62\x06proto3'
)



_COMPUTATIONDATA_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='ComputationData.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_DIM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_TRIPLET', index=2, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIPLE_ARRAY', index=3, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUL_DATA_SHARE', index=4, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUL_OwnVal_SHARE', index=5, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUL_OtherVal_SHARE', index=6, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECEIVED_OK', index=7, number=99,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=97,
  serialized_end=245,
)
_sym_db.RegisterEnumDescriptor(_COMPUTATIONDATA_TYPE)


_COMPUTATIONDATA = _descriptor.Descriptor(
  name='ComputationData',
  full_name='ComputationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ComputationData.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='python_bytes', full_name='ComputationData.python_bytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPUTATIONDATA_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=245,
)

_COMPUTATIONDATA.fields_by_name['type'].enum_type = _COMPUTATIONDATA_TYPE
_COMPUTATIONDATA_TYPE.containing_type = _COMPUTATIONDATA
DESCRIPTOR.message_types_by_name['ComputationData'] = _COMPUTATIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputationData = _reflection.GeneratedProtocolMessageType('ComputationData', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:ComputationData)
  })
_sym_db.RegisterMessage(ComputationData)



_MPCSERVICE = _descriptor.ServiceDescriptor(
  name='MPCService',
  full_name='MPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=247,
  serialized_end=319,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetComputationData',
    full_name='MPCService.GetComputationData',
    index=0,
    containing_service=None,
    input_type=_COMPUTATIONDATA,
    output_type=_COMPUTATIONDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MPCSERVICE)

DESCRIPTOR.services_by_name['MPCService'] = _MPCSERVICE

# @@protoc_insertion_point(module_scope)
